### ISSUE TITLE
Date formats with data step views need some prep

### ISSUE THREAD

**Issue by dckc** [PCORnet-DRN-OC/PCORnet-Diagnostic-Query#2]
@mprittie found it necessary to do some prep work: [data_step_view_prep.sas](https://github.com/mprittie/i2p-transform/blob/master/SAS/data_step_view_prep.sas).

I think perhaps there's documentation that this sort of thing is necessary, but I just looked for it without luck.

cc @njgraham

**Comment by rusincovitch** [comment]
Hi @dckc - this seems perhaps similar to this thread: [https://pcornet.imeetcentral.com/networkcollaboration/forumentry/43486181/](https://pcornet.imeetcentral.com/networkcollaboration/forumentry/43486181/)

What do you think?

**Comment by rusincovitch** [comment]
Hi @dckc - just to check in with you about the prep work your team was generous to share.

Do you have any plans to post this script on GitHub or iMeetCentral? It would be great if we could link to this as a resource for any other sites using data step views.

**Comment by mprittie** [comment]
Hi @rusincovitch, I forked this repository to [kumc-bmi/PCORnet-Diagnostic-Query](https://github.com/kumc-bmi/PCORnet-Diagnostic-Query), where I added the SAS scripts I wrote to generate and validate the data-step-views we are using for both the diagnostic and data characterization queries.

I could send you a pull request if you would like, so that you could easily accept these file into this repository for others to use (and potentially improve).

**Comment by rusincovitch** [comment]
@mprittie, this is great!

Am I understanding your scripts correctly as being pre-processing stages that would be applicable to an Oracle database supporting data step view for SAS?

**Comment by mprittie** [comment]
@rusincovitch, that's correct.  The [data_step_views](https://github.com/kumc-bmi/PCORnet-Diagnostic-Query/tree/master/data_step_views) directory contains three files:

- `configuration.example.sas`: An example configuration file, which contains environment specific configuration statements.
- `data_step_view_prep.sas`: Creates the data-step-view library files, using the Oracle database connection and library path specified in the configuration file.
- `data_step_view_inspect.sas`:  Runs `proc contents` and `proc sql` statements to gather informations about the data-step-views and returns the first ten rows from each CDMv3 table.  This provides a quick glimpse of the data-step-views to validate that they are working and structured correctly.

I will send you a pull request, so that you can then merge them into this repository if you'd like.  Let me know if you have any questions.

**Comment by rusincovitch** [comment]
Thank you for this explanation, @mprittie – this is very helpful and will be a great resource!

We appreciate the pull request, but SAS data step views aren’t part of the foundational query package, and many data partners aren’t using this configuration.

So instead, I’m posting a link to this resource in our PCORnet network collaborative discussion space at [https://pcornet.imeetcentral.com/networkcollaboration/forumentry/44791895] (https://pcornet.imeetcentral.com/networkcollaboration/forumentry/44791895). 

I’ve quoted your description to help the group relate this to their own infrastructures because we have a lot of heterogeneity among data partners.

Thanks again, and looking forward to more discussion with you!

**Comment by mprittie** [comment]
Sure thing @rusincovitch, I'm glad we could contribute to this effort!
